# Generated by Django 4.1.7 on 2023-03-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("length", models.DecimalField(decimal_places=2, max_digits=5)),
                ("zip_from", models.CharField(max_length=8)),
                ("zip_to", models.CharField(max_length=8)),
            ],
        ),
    ]
